#!/bin/bash
# Logs into an AWS EC2 instance using EC2 Instance Connect (if supported).
# Usage: aws-ec2-instance-connect INSTANCE_ID [SSH_OPTIONS]
set -euo pipefail
go run main.go check-requirements -q

instance=$1
shift
instance_ip=$(aws ec2 describe-instances --instance-ids "$1" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
tmpdir=$(mktemp -d)

ssh-keygen -f "$tmpdir/id_rsa" -N ''
aws ec2-instance-connect send-ssh-public-key --instance-id "$instance" --instance-os-user ec2-user --ssh-public-key "$(cat "$tmpdir/id_rsa.pub")" >/dev/null
ssh ec2-user@"$instance_ip" -i "$tmpdir"/id_rsa

# Delete the temporary key.
rm -rf "$tmpdir"
