#!/bin/bash
# List all Kubernetes resources that have finalizers.
# Usage: k8s-list-resources-with-finalizers [kubectl get options]

go run main.go check-requirements -q
pipe=$(mktemp -u)
mkfifo "$pipe"
for kind in $(kubectl api-resources --no-headers | awk '{print $1}'); do
    kubectl get "$kind" "$@" --output json |
        jq -r '
        (
            .items[] |
            select(.metadata.finalizers) |
            [
                if .metadata.namespace then .metadata.namespace else "<none>" end,
                .apiVersion + "/" + .kind,
                .metadata.name,
                (.metadata.finalizers | join(","))
            ]
        ) |
        @tsv
        ' >>"$pipe" &
done
echo "NAMESPACE TYPE NAME FINALIZERS
$(cat "$pipe")" | column -t
rm "$pipe"
