#!/bin/bash
# List all Kubernetes resources with IP addresses
# Usage: k8s-list-ip-addresses [kubectl get options]
#
# Copyright © 2025 Gino Latorilla
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
set -euo pipefail

go run main.go check-requirements -q
cat <(echo NAMESPACE NAME KIND INTERNAL_ADDRESSES EXTERNAL_ADDRESSES) \
    <(
        kubectl get services "$@" -o json |
            jq -r '
            .items[] |
            select(
                .type != "ExternalName" and
                .spec.clusterIP and
                .spec.clusterIP != "None"
            ) |
            [
                .metadata.namespace,
                .metadata.name,
                .kind,
                (.spec.clusterIPs | join(",")),
                (.spec.externalIPs // [] | join(","))
            ] |
            @tsv
            '
    ) \
    <(
        kubectl get pods "$@" -o json |
            jq -r '
            .items[] |
            [
                .metadata.namespace,
                .metadata.name,
                .kind,
                ([.status.podIPs[].ip] | join(","))
            ] |
            @tsv
            '
    ) \
    <(
        kubectl get nodes "$@" -o json |
            jq -r '
            .items[] |
            [
                "<none>",
                .metadata.name,
                .kind,
                ([.status.addresses[] | select(.type=="InternalIP") | .address] | join(",")),
                ([.status.addresses[] | select(.type=="ExternalIP") | .address] | join(","))
            ] |
            @tsv
            '
    ) |
    column -t
