#!/bin/bash
# List all Kubernetes secrets that are certs.
# Usage: k8s-list-certs [kubectl get options]
set -euo pipefail

go run main.go check-requirements -q
kubectl get secret "$@" --output json |
    jq -r '
    ["NAMESPACE", "NAME", "EXPIRATION"],
    (
        .items[] |
        select(.type == "kubernetes.io/tls") |
        [
            .metadata.namespace,
            .metadata.name,
            "{{ $pemb64 := `\(.data."tls.crt")` }}{{ index ($pemb64 | b64dec | x509) `NotAfter` | relativeTime }}"
        ]
    ) |
    @tsv
    ' |
    go run main.go template |
    column -t -s $'\t'
