#!/bin/bash
# Finds Kubernetes resources that have the given IP address
# Usage: k8s-lookup-address IP_ADDR [kubectl get options]
set -euo pipefail

go run main.go check-requirements -q
export address="$1"
shift
cat <(echo NAMESPACE NAME KIND) \
    <(
        kubectl get services "$@" -o json |
            jq -r '
            .items[] |
            select(
                .spec.clusterIPs[] | contains(env.address)
            ) |
            [
                .metadata.namespace,
                .metadata.name,
                .kind
            ] |
            @tsv
            '
    ) \
    <(
        kubectl get pods "$@" -o json |
            jq -r '
            .items[] |
            select(
                .status.podIPs[].ip | contains(env.address)
            ) |
            [
                .metadata.namespace,
                .metadata.name,
                .kind
            ] |
            @tsv
            '
    ) \
    <(
        kubectl get nodes "$@" -o json |
            jq -r '
            .items[] |
            select(
                .status.addresses[].address  | contains(env.address)
            ) |
            [
                "<none>",
                .metadata.name,
                .kind
            ] |
            @tsv
            '
    ) |
    column -t
