#!/bin/bash
# Prints how much time is left until the TLS certificate expires.
# Usage: tls-cert-ttl CERTIFICATE
set -euo pipefail

go run main.go check-requirements -q
openssl x509 \
    -in "$1" \
    -noout \
    -dateopt iso_8601 \
    -dates |
    go run main.go tls-cert-countdown
