#!/bin/bash
# Logs into an AWS EC2 instance using EC2 Instance Connect (if supported).
# Usage: aws-ec2-instance-connect INSTANCE_ID [SSH_OPTIONS]
#
# Copyright © 2025 Gino Latorilla
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
set -euo pipefail
devops check-requirements -q

instance=$1
shift
instance_ip=$(aws ec2 describe-instances --instance-ids "$1" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
tmpdir=$(mktemp -d)

ssh-keygen -f "$tmpdir/id_rsa" -N ''
aws ec2-instance-connect send-ssh-public-key --instance-id "$instance" --instance-os-user ec2-user --ssh-public-key "$(cat "$tmpdir/id_rsa.pub")" >/dev/null
ssh ec2-user@"$instance_ip" -i "$tmpdir"/id_rsa

# Delete the temporary key.
rm -rf "$tmpdir"
