#!/bin/bash
# List all Kubernetes resources that have finalizers.
# Usage: k8s-list-resources-with-finalizers [kubectl get options]
#
# Copyright © 2025 Gino Latorilla
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
devops check-requirements -q
pipe=$(mktemp -u)
mkfifo "$pipe"
for kind in $(kubectl api-resources --no-headers | awk '{print $1}'); do
    kubectl get "$kind" "$@" --output json |
        jq -r '
        (
            .items[] |
            select(.metadata.finalizers) |
            [
                if .metadata.namespace then .metadata.namespace else "<none>" end,
                .apiVersion + "/" + .kind,
                .metadata.name,
                (.metadata.finalizers | join(","))
            ]
        ) |
        @tsv
        ' >>"$pipe" &
done
echo "NAMESPACE TYPE NAME FINALIZERS
$(cat "$pipe")" | column -t
rm "$pipe"
