#!/bin/bash
# List all Kubernetes Pods that reference a resource by name
# Usage: k8s-list-resource-users KIND/NAME [kubectl get options]
#
# Copyright © 2025 Gino Latorilla
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
set -euo pipefail

devops check-requirements -q
[[ $# -ge 1 ]] || {
    echo "Usage: $0 KIND/NAME [kubectl get options]" >&2
    exit 1
}
export resource="${1}"
shift
resource="$(kubectl get "${resource}" "$@" -ojson | jq -r '.metadata.name')"
kubectl get pods "$@" -o json |
    jq -r '
    ["NAMESPACE", "POD"],
    (
        [
            .items[] |
            select(.spec | .. | .name?==env.resource) |
            [
                .metadata.namespace,
                .metadata.name
            ]
        ] | 
        unique 
        .[]
    ) | @tsv
    ' |
    column -t
